# Generated by Django 3.2 on 2021-05-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dj_student',
            fields=[
                ('st_id', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=20)),
            ],
        ),
    ]
