# Generated by Django 3.2 on 2021-05-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dj_student',
            new_name='student',
        ),
    ]
