# Generated by Django 3.2 on 2021-05-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_rename_dj_student_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='st_name',
            field=models.CharField(max_length=25),
        ),
    ]
